classdef TyrePlotFrictionEllipsePanel < matlab.ui.componentcontainer.ComponentContainer
    %TYREPLOTFRICTIONELLIPSEPANEL Plots friction ellipse of tyre model.
    
    properties
        Model MagicFormulaTyre = MagicFormulaTyre.empty
    end
    properties (Access = private, Transient, NonCopyable)
        MainGrid                    matlab.ui.container.GridLayout
        Axes                        ui.FrictionEllipseAxes
        SidePanel                   matlab.ui.container.Panel
        SidePanelGrid               matlab.ui.container.GridLayout
    end
    properties (Access = private)
        Settings settings.AppSettings
        SettingsChangedListener event.listener
    end
    events (NotifyAccess = public)
        TyreModelChanged
        TyreDataChanged
    end
    methods (Access = private)
        function onModelChanged(obj, ~, event)
            model = event.Model;
            obj.Model = model;
            obj.Axes.Model = model;
        end
        function onDataChanged(obj, ~, event)
            % TODO: data not used as of now.
        end
        function onPlotSettingsChanged(obj, source, event)
            s = obj.Settings;
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            tag = source.Tag;
            switch tag
                case 'AxisEqual'
                    value = event.Value;
                    s.AxisEqual = value;
                case 'AxisManualLimits'
                    value = event.Value;
                    s.AxisManualLimits = value;
                case 'XLimit'
                    value = event.Value;
                    s.Limits(1) = value;
                case 'YLimit'
                    value = event.Value;
                    s.Limits(2) = value;
                case 'Legend'
                    value = event.Value;
                    s.LegendOn = value;
                case 'Marker'
                    value = event.Value;
                    s.Marker = value;
                case 'MarkerSize'
                    value = event.Value;
                    s.MarkerSize = value;
                case 'LineWidth'
                    value = event.Value;
                    s.LineWidth = value;
                case 'MaxLONGSLIP'
                    value = event.Value;
                    value = value/100;
                    s.LONGSLIP_Max = value;
                case 'MaxSLIPANGL'
                    value = event.Value;
                    s.SLIPANGL_Max = value;
                case 'StepLONGSLIP'
                    value = event.Value;
                    value = value/100;
                    s.LONGSLIP_Step = value;
                case 'StepSLIPANGL'
                    value = event.Value;
                    s.SLIPANGL_Step = value;
            end
            update(obj.Axes)
        end
        function onSteadyStateSettingsChanged(obj, source, event)
            s = obj.Settings;
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            tag = source.Tag;
            value = event.Value;
            switch tag
                case 'INFLPRES'
                    bar2pascal = @(x) x*1E5;
                    s.INFLPRES = bar2pascal(value);
                case 'INCLANGL'
                    s.INCLANGL = deg2rad(value);
                case 'FZW'
                    s.FZW = value;
                case 'TYRESIDE'
                    s.TYRESIDE = value;
            end
            update(obj.Axes)
        end
    end
    methods(Access = protected)
        function updateSidebarState(obj)
            show = obj.Settings.View.TyreAnalysisPanel.ShowSidebar;
            sidebar = obj.SidePanel;
            axes = obj.Axes;
            if show
                set(sidebar, 'Visible', 'on')
                axes.Layout.Column = 1;
            else
                set(sidebar, 'Visible', 'off')
                axes.Layout.Column = [1 2];
            end
        end
    end
    methods(Access = protected)
        function setupMainGrid(obj)
            s = obj.Settings.Layout;
            w = s.DefaultSidebarWidth;
            obj.MainGrid = uigridlayout(obj, ...
                'RowHeight', {'1x'}, ...
                'ColumnWidth', {'1x', w}, ...
                'ColumnSpacing', s.DefaultColumnSpacing, ...
                'Padding', 0*ones(1,4), ...
                'Scrollable', false);
        end
        function setupSidePanel(obj)
            obj.SidePanel = uipanel(obj.MainGrid);
            
            obj.SidePanelGrid = uigridlayout(obj.SidePanel, ...
                'RowHeight', repmat({'fit'}, 1, 2), ...
                'ColumnWidth', {'1x'}, ...
                'ColumnSpacing', 0, ...
                'Padding', zeros(1,4), ...
                'Scrollable', true);
        end
        function setupPlotSettings(obj)
            s = obj.Settings;
            p = uipanel(obj.SidePanelGrid, ...
                'Title', 'Plot Settings', ...
                'FontWeight', s.Text.FontWeightPanel, ...
                'FontName', s.Text.FontNamePanel, ...
                'BorderType', 'none');
            w = s.Layout.DefaultButtonWidthTextIcon;
            g = uigridlayout(p, ...
                'RowHeight', repmat({'fit'}, 1, 9), ...
                'ColumnWidth', {w, 'fit'}, ...
                'ColumnSpacing', s.Layout.DefaultColumnSpacing, ...
                'Padding', s.Layout.DefaultPadding, ...
                'Scrollable', false);
            
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            uibutton(g, 'state', 'Text', 'Equal', 'Value', true, ...
                'Tag', 'AxisEqual', ...
                'Value', s.AxisEqual, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'Axis');
           
            uibutton(g, 'state', 'Text', 'Manual', 'Value', true, ...
                'Tag', 'AxisManualLimits', ...
                'Value', s.AxisManualLimits, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged); 
            uilabel(g, 'Text', 'Limits');
           
            uieditfield(g, 'numeric', 'Value', 4000, ...
                'Tag', 'XLimit', ...
                'ValueDisplayFormat', '%.0f [N]', ...
                'Value', s.Limits(1), ...
                'Limits', [0 100E3], 'LowerLimitInclusive', false, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'X-Limit');
   
            uieditfield(g, 'numeric', 'Value', 4000, ...
                'Tag', 'YLimit', ...
                'ValueDisplayFormat', '%.0f [N]', ...
                'Value', s.Limits(2), ...
                'Limits', [0 100E3], 'LowerLimitInclusive', false, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);         
            uilabel(g, 'Text', 'Y-Limit');

            uieditfield(g, 'numeric', 'Value', 15, ...
                'Tag', 'MaxSLIPANGL', ...
                'Limits', [-90 90], ...
                'Value', s.SLIPANGL_Max, ...
                'ValueDisplayFormat', '%.1f [deg]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'SLIPANGL (Max)');

            uieditfield(g, 'numeric', 'Value', 1, ...
                'Tag', 'StepSLIPANGL', ...
                'Limits', [-90 90], ...
                'Value', s.SLIPANGL_Step, ...
                'ValueDisplayFormat', '%.1f [deg]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'SLIPANGL (Step)');

            uieditfield(g, 'numeric', 'Value', 15, ...
                'Tag', 'MaxLONGSLIP', ...
                'Limits', [-1 1]*100, ...
                'Value', s.LONGSLIP_Max, ...
                'ValueDisplayFormat', '%.1f [%%]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'LONGSLIP (Max)');
            
            uieditfield(g, 'numeric', 'Value', 1, ...
                'Tag', 'StepLONGSLIP', ...
                'Limits', [-1 1]*100, ...
                'Value', s.LONGSLIP_Step, ...
                'ValueDisplayFormat', '%.1f [%%]', ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged);
            uilabel(g, 'Text', 'LONGSLIP (Step)');

            markers = {'none', '.', '+', 'o', '*', 'x', 'square', ...
                'diamond', '^', 'v', '>', '<', 'pentagram', 'hexagram'};
            uidropdown(g, 'Items', markers, ...
                'Value', s.Marker, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged, ...
                'Tag', 'Marker');
            uilabel(g, 'Text', 'Marker');

            uispinner(g, 'Value', 15, ...
                'Limits', [0 100], 'LowerLimitInclusive', 'off', ...
                'Value', s.MarkerSize, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged, ...
                'Tag', 'MarkerSize');            
            uilabel(g, 'Text', 'Marker Size');
           
            uispinner(g, 'Value', 1, ...
                'Limits', [0 10], 'LowerLimitInclusive', 'off', ...
                'Value', s.LineWidth, ...
                'ValueChangedFcn', @obj.onPlotSettingsChanged, ...
                'Tag', 'LineWidth'); 
            uilabel(g, 'Text', 'Line Width');
        end
        function setupSteadyStateSettings(obj)
            s = obj.Settings;
            p = uipanel(obj.SidePanelGrid, ...
                'Title', 'Steady-State Settings', ...
                'FontWeight', s.Text.FontWeightPanel, ...
                'FontName', s.Text.FontNamePanel, ...
                'BorderType', 'none');
            w = s.Layout.DefaultButtonWidthTextIcon;
            g = uigridlayout(p, ...
                'RowHeight', repmat({'fit'}, 1, 6), ...
                'ColumnWidth', {'fit', w, 'fit'}, ...
                'ColumnSpacing', s.Layout.DefaultColumnSpacing, ...
                'Padding', s.Layout.DefaultPadding, ...
                'Scrollable', false);
            
            s = s.View.TyreAnalysisPanel.TyrePlotFrictionEllipsePanel;
            uilabel(g, 'Text', 'INCLANGL');
            uispinner(g, 'Value', 0, 'Step', 1, 'Limits', [-90 90], ...
                'Value', rad2deg(s.INCLANGL), ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Tag', 'INCLANGL');
            uilabel(g, 'Text', '[deg]', ...
                'HorizontalAlignment', 'center');
            
            pascal2bar = @(x) x*1E-5;
            uilabel(g, 'Text', 'INFLPRES');
            uispinner(g, 'Value', 0.8, 'Step', 0.1, ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Value', pascal2bar(s.INFLPRES), ...
                'Limits', [0 100], 'LowerLimitInclusive', 'off', ...
                'Tag', 'INFLPRES');
            uilabel(g, 'Text', '[bar]', ...
                'HorizontalAlignment', 'center');
            
            uilabel(g, 'Text', 'FZW');
            uispinner(g, 'Value', 1000, 'Step', 100, ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Value', s.FZW, ...
                'Limits', [0 100E3], 'LowerLimitInclusive', 'off', ...
                'Tag', 'FZW');
            uilabel(g, 'Text', '[N]', ...
                'HorizontalAlignment', 'center');
            
            uilabel(g, 'Text', 'TYRESIDE');
            uidropdown(g, 'Items', {'LEFT', 'RIGHT'}, ...
                'ItemsData', {0, 1}, ...
                'ValueChangedFcn', @obj.onSteadyStateSettingsChanged, ...
                'Value', s.TYRESIDE, ...
                'Tag', 'TYRESIDE');
        end
        function setupAxes(obj)
            ax = ui.FrictionEllipseAxes(obj.MainGrid, ...
                'Model', obj.Model);
            obj.Axes = ax;
        end
        function setupListeners(obj)
            addlistener(obj, 'TyreModelChanged', @obj.onModelChanged);
            addlistener(obj, 'TyreDataChanged', @obj.onDataChanged);
            s = obj.Settings.View.TyreAnalysisPanel;
            obj.SettingsChangedListener = listener(...
                s, 'SettingsChanged', @(~,~) obj.update());
        end
    end
    methods (Access = protected)
        function setup(obj)
            set(obj, 'Position', [0 0 800 400])
            obj.Settings = settings.AppSettings();
            setupMainGrid(obj)
            setupAxes(obj)
            setupSidePanel(obj)
            setupPlotSettings(obj)
            setupSteadyStateSettings(obj)
            setupListeners(obj)
        end
        function update(obj)
            updateSidebarState(obj)
        end
    end
end
